name: buildisis v1

on:
  push:
   branches: [ stable-r1.9 ]
  workflow_dispatch:
    inputs:
      BUILD_TITLE:
        description: 'Custom Build Title'
        required: false
      KERNEL_TREE:
        description: 'Kernel Tree'
        default: 'https://github.com/harunaltair/kernel_xiaomi_peridot'
        required: true
      KERNEL_TREE_BRANCH:
        description: 'Kernel Tree Branch'
        required: true
        default: 'stable-r1.9'
      CODENAME:
        description: 'Phone Codename'
        default: 'peridot'
        required: true
      KERNELSU_OPTION:
        description: 'Choose KernelSU setup option (1: next, 2: next-susfs, 3: none)'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Display User Inputs
      run: |
        echo "::group::User Environment Variables"
        echo "Custom Build Title: ${{ github.event.inputs.BUILD_TITLE }}"
        echo "Kernel Tree: ${{ github.event.inputs.KERNEL_TREE }}/tree/${{ github.event.inputs.KERNEL_TREE_BRANCH }}"
        echo "Codename: ${{ github.event.inputs.CODENAME }}"
        echo "KernelSU Option: ${{ github.event.inputs.KERNELSU_OPTION }}"
        echo "::endgroup::"

    - name: Generate Build Date
      id: build_date
      run: |
        build_date=$(date +"%Y%m%d")  
        echo "build_date=$build_date" >> $GITHUB_OUTPUT

    - name: Initialize workspace
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
        echo "build_title=${{ github.event.inputs.BUILD_TITLE || github.event.inputs.CODENAME }}" >> $GITHUB_OUTPUT
      id: workspace

    - name: Prepare the build environment
      run: |
        sudo apt update -y
        sudo apt install -y flex bison libncurses-dev libssl-dev bc build-essential git ccache binutils-aarch64-linux-gnu
        mkdir -p $HOME/tc
        cd $HOME/tc
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
        mkdir clang
        tar -xf clang.tar.gz -C clang
        echo "tools-folder=$HOME/tc/clang" >> $GITHUB_OUTPUT
      id: tools

    - name: Clone kernel source
      working-directory: ${{ steps.workspace.outputs.workspace-folder }}
      run: |
       KERNEL_TREE="${{ github.event.inputs.KERNEL_TREE }}"
       KERNEL_TREE_BRANCH="${{ github.event.inputs.KERNEL_TREE_BRANCH }}"

       if [ -z "$KERNEL_TREE" ]; then
        KERNEL_TREE="https://github.com/harunaltair/kernel_xiaomi_peridot"
       fi

       if [ -z "$KERNEL_TREE_BRANCH" ]; then
        KERNEL_TREE_BRANCH="stable-r1.9"
       fi

       git clone --depth=1 $KERNEL_TREE -b $KERNEL_TREE_BRANCH kernel_tree

       echo "kernel-folder=$(pwd)/kernel_tree" >> $GITHUB_OUTPUT
       working-directory: ${{ steps.workspace.outputs.workspace-folder }}
       id: kernel

    - name: Building kernel
      run: |
        rm -rf KernelSU-Next

        if [[ "${{ github.event.inputs.KERNELSU_OPTION }}" == '1' ]]; then
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
        elif [[ "${{ github.event.inputs.KERNELSU_OPTION }}" == '2' ]]; then
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
        fi

        export PATH="$HOME/tc/clang/bin:$PATH"
        export LD_LIBRARY_PATH=${HOME}/tc/clang/lib64:$LD_LIBRARY_PATH

        DATE=$(date '+%Y%m%d-%H%M')
        OUT_DIR=out/
        VERSION="agmad-isis-PERIDOT-${DATE}"

        COUNT="$(grep -c '^processor' /proc/cpuinfo)"
        KEBABS="$COUNT"

        ARGS="ARCH=arm64 \
        O=${OUT_DIR} \
        CC=clang \
        LD=ld.lld \
        CLANG_TRIPLE=aarch64-linux-gnu- \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
        -j${KEBABS}"

        make -j${KEBABS} ${ARGS} peridot_defconfig
        cd ${OUT_DIR}
        make -j${KEBABS} ${ARGS} CC="ccache clang" HOSTCC="ccache gcc" HOSTCXX="cache g++" olddefconfig
        cd ../
        make -j${KEBABS} ${ARGS} CC="ccache clang" HOSTCC="ccache gcc" HOSTCXX="ccache g++" 2>&1 | tee build.log

        if [ -f "out/arch/arm64/boot/Image.gz" ]; then
            git clone -q https://github.com/ahmedtohamy1/ak3 -b peridot ak3
            cp out/arch/arm64/boot/Image.gz ak3
            cd ak3
            zip -r9 "../${VERSION}.zip" * -x '*.git*' README.md *placeholder >> /dev/null
            cd ..
            rm -rf ak3
            echo "zipname=${VERSION}.zip" >> $GITHUB_OUTPUT
        else
            echo "Compilation Failed!"
            exit 1
        fi
      working-directory: ${{ steps.kernel.outputs.kernel-folder }}
      id: build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-peridot
        path: ${{ steps.kernel.outputs.kernel-folder }}/${{ steps.build.outputs.zipname }}
